# Generated by Django 5.0.6 on 2024-06-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_background_image_homepage_botton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='botton_text',
            field=models.CharField(blank=True, help_text='Subheading text undet the banner title', max_length=140),
        ),
    ]
